### ISSUE TITLE
Homework: Find api endpoints for the project and design a basic frame work

### ISSUE THREAD

**Issue by omarwright07** [omarwright07/music-guru#3]
Add whenever Store API endpoints that we can find to this issue

**Comment by bagl0025** [comment]
Kroger has and API: https://www.programmableweb.com/api/kroger-rest-api-v121.
NOTE: It requires OAuth2 authentication.
I've searched for Walmart, Costco, Whole Foods, Target, etc. and they seem to be meant for their partnors and other vendors - not individual use.  I found a 3rd party API for Walmart, but it's not free.
